package com.aerosentinel.dto.evidence;

import com.aerosentinel.hotspot.HotspotSpatialContext.*;
import com.aerosentinel.forecast.ForecastResponse.ForecastItem;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Authoritative Unified Response Contract for Feature 5 (Evidence & WHY Diagnostic Layer).
 *
 * Strictly separates:
 * 1. Context: cell, city, prediction, event, and snapshot lineage
 * 2. Observed Facts: physical sensor telemetry (air, weather, GIS, coverage)
 * 3. Model Outputs: ML Hotspot probability & Multi-Horizon Forecast trajectories
 * 4. Evidence / Alert Support: multi-source signals, weights, and triage classification
 * 5. AI Interpretation: grounded public and analyst narratives generated by Gemini / Fallback
 * 6. Recommended Verification: prioritized operational field action directives
 * 7. Provenance: end-to-end model and scoring versions
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record EvidenceSummaryResponse(
        ContextDto context,
        ObservedFactsDto observedFacts,
        ModelOutputsDto modelOutputs,
        EvidenceDto evidence,
        AiInterpretationDto aiInterpretation,
        RecommendedVerificationDto recommendedVerification,
        ProvenanceDto provenance,
        String status
) {

    public record ContextDto(
            String h3Index,
            String cityId,
            String cityName,
            String predictionId,
            String featureSnapshotId,
            String eventId,
            String eventCode,
            Instant generatedAt
    ) {
        public ContextDto(
                String h3Index,
                String cityId,
                String cityName,
                String predictionId,
                String featureSnapshotId,
                Instant generatedAt
        ) {
            this(h3Index, cityId, cityName, predictionId, featureSnapshotId, null, null, generatedAt);
        }
    }

    public record ObservedFactsDto(
            AirContext air,
            WeatherContext weather,
            MonitoringCoverageContext monitoringCoverage,
            SpatialDispersionContext spatialDispersion,
            EnvironmentalGisContext gisContext
    ) {}

    public record ModelOutputsDto(
            HotspotModelOutputDto hotspot,
            ForecastModelOutputDto forecast
    ) {}

    public record HotspotModelOutputDto(
            Double riskScore,
            Double operationalThreshold,
            Boolean isHotspot,
            String riskLevel,
            Double confidence,
            ConfidenceBreakdown confidenceBreakdown,
            String modelVersion,
            String engineType
    ) {}

    public record ForecastModelOutputDto(
            Instant baseTimestamp,
            Instant generatedAt,
            String forecastModelVersion,
            UUID parentPredictionId,
            Double forecastConfidence,
            List<ForecastItem> horizons
    ) {
        public ForecastModelOutputDto(
                Instant baseTimestamp,
                Instant generatedAt,
                String forecastModelVersion,
                Double forecastConfidence,
                List<ForecastItem> horizons
        ) {
            this(baseTimestamp, generatedAt, forecastModelVersion, null, forecastConfidence, horizons);
        }
    }

    public record EvidenceDto(
            List<EvidenceSignalDto> signals,
            Double evidenceScore,
            ScoreBreakdownDto scoreBreakdown,
            String consistency,
            String triageState,
            Map<String, String> sourceMatrix,
            List<String> unavailableSources,
            List<String> conflictingNotes,
            List<String> clusterH3Cells
    ) {
        public EvidenceDto(
                List<EvidenceSignalDto> signals,
                Double evidenceScore,
                ScoreBreakdownDto scoreBreakdown,
                String consistency,
                String triageState,
                Map<String, String> sourceMatrix,
                List<String> unavailableSources,
                List<String> conflictingNotes
        ) {
            this(signals, evidenceScore, scoreBreakdown, consistency, triageState, sourceMatrix, unavailableSources, conflictingNotes, Collections.emptyList());
        }
    }

    public record EvidenceSignalDto(
            String signalId,
            String sourceType,
            String description,
            Instant timestamp,
            Double confidenceScore,
            String dataSource,
            String relevanceTier,
            String sourceRef
    ) {}

    public record ScoreBreakdownDto(
            Double observationStrength,
            Double mlForecastSupport,
            Double multiSourceAgreement,
            Double spatialConsistency,
            Double temporalPersistence,
            Double recencyFactor,
            Double conflictPenalty,
            Double evidenceCompleteness,
            Double finalEvidenceScore
    ) {}

    public record AiInterpretationDto(
            String summaryPublic,
            String summaryAnalyst,
            String detectedCondition,
            List<String> supportingSignals,
            String forecastTrajectory,
            String uncertaintyStatement,
            List<String> unsupportedConclusions,
            Boolean causalClaimSupported,
            Boolean isGrounded,
            String modelVersion,
            String promptVersion
    ) {}

    public record RecommendedVerificationDto(
            String action,
            String priority,
            List<String> guidelines
    ) {}

    public record ProvenanceDto(
            String h3Index,
            String cityId,
            String f3PredictionId,
            String f3ModelVersion,
            String f4ModelVersion,
            String f5ScoringVersion,
            String geminiModelVersion,
            String geminiPromptVersion,
            Instant evaluatedAt
    ) {}
}
